

# This file was *autogenerated* from the file LCM_graph_small_groups.sage
from sage.all_cmdline import *   # import sage library

_sage_const_45 = Integer(45); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
import pandas as pd
import networkx as nx
from pyvis.network import Network
from IPython.core.display import display, HTML

# max order to compute comm graph
max_order = _sage_const_45 
gap('LoadPackage("GGraph");')

small_groups = gap(f'AllSmallGroups([1..{max_order}], x->(not IsAbelian(x)));')

for G in list(small_groups):
    # Pega o isomorfismo com subgrupo do grupo de perm.
    # Para questões de visualização nos grafos
    G_hom = gap.function_call('IsomorphismPermGroup', G)
    G = gap.function_call('Image', G_hom) 
    elements_list = list(gap.function_call('Elements', G))
    source = []
    target = []
    # Plots Commutative graph using GGraph package
    com_graph = gap.function_call('LCMGraph', [G]) 
    grape_graph = gap.get_record_element(com_graph, 'graph')
    sanity_check = _sage_const_0 

    for idx, e1 in enumerate(elements_list):
        adjacency = gap.function_call('Adjacency', [grape_graph, idx+_sage_const_1 ])
        for e_idx in adjacency:
            if e1 == elements_list[int(e_idx)-_sage_const_1 ]:
                pass
            else:
                source.append(str(e1))
                target_elm = elements_list[int(e_idx)-_sage_const_1 ]
                target.append(str(target_elm))
    
    data = {'Source': source,
            'Target': target}

    df = pd.DataFrame(data)
    graph = nx.from_pandas_edgelist(df,
                                    source='Source',
                                    target='Target')

    net = Network(height='1000px', width='80%', heading='')

    group_id = list(gap.function_call('IdGroup', [G]))

    net.from_nx(graph)
    net.show_buttons()
    #net.show('example2.html')
    file_str = f'LCM_graph_plots/{group_id[_sage_const_0 ]}_{group_id[_sage_const_1 ]}_LCM_graph.html'
    net.save_graph(file_str)
    # display(HTML('example.html'))

